#!/bin/bash

TEXT_WITH_VERSION=`../sampctl --version | grep "sampctl.conf"`

if [ -z "$TEXT_WITH_VERSION" ]
then
    echo "Cannot find sampctl.conf info in sampctl with --version command!" >&2
    exit 1
fi

exit 0