#!/bin/bash

UNINSTALL_RELEASE_AFTERWARDS=0

TEXT_WITH_INSTALLED_RELEASE=`../sampctl list-releases | grep '[x] samp03xsvr_R2_patch1'`

if [ -z "$TEXT_WITH_INSTALLED_RELEASE" ]
then
    ../sampctl install-release samp03xsvr_R2_patch1 > /dev/null
    if [ "$?" != 0 ]
    then
        exit 1
    fi
    let "UNINSTALL_RELEASE_AFTERWARDS = 1"
fi

TEXT_WITH_VERSION=`../sampctl list-servers | grep "^- ernie"`

if [ ! -z "$TEXT_WITH_VERSION" ]
then
    exit 1
fi

../sampctl create-server ernie samp03xsvr_R2_patch1 45678 thisisfortestingonly > /dev/null
if [ "$?" != 0 ]
then
    exit 1
fi

../sampctl delete-server ernie > /dev/null
if [ "$?" != 0 ]
then
    exit 1
fi

if [ "$UNINSTALL_RELEASE_AFTERWARDS" == "1" ]
then
    ../sampctl uninstall-release samp03xsvr_R2_patch1 > /dev/null
    if [ "$?" != 0 ]
    then
        exit 1
    fi
fi
